import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronLeft, Accessibility, CheckCircle2, ShieldAlert, Globe, FileKey, Download, Rocket } from "lucide-react";

interface BlinkAccessibilityTesterProps {
  isActive: boolean;
  onExit: () => void;
}

export default function BlinkAccessibilityTester({ isActive, onExit }: BlinkAccessibilityTesterProps) {
  const [appState, setAppState] = useState<"MAIN_MENU" | "URL_SELECT" | "TEST_SELECT" | "GENERATING_VIEW" | "RESULTS_VIEW">("MAIN_MENU");
  const [activeIndex, setActiveIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const [selectedUrl, setSelectedUrl] = useState<string | null>(null);
  const [selectedTest, setSelectedTest] = useState<string | null>(null);

  const [terminalLines, setTerminalLines] = useState<string[]>([]);
  const intervalRef = useRef<number | null>(null);

  const synth = typeof window !== "undefined" ? window.speechSynthesis : null;
  const speak = (text: string) => {
    if (!synth) return;
    synth.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    synth.speak(utterance);
  };

  const simulateTerminal = async (lines: string[], onComplete: () => void) => {
    setAppState("GENERATING_VIEW");
    setTerminalLines([]);
    for (let i = 0; i < lines.length; i++) {
      await new Promise((r) => setTimeout(r, 600));
      setTerminalLines((prev) => [...prev, lines[i]]);
      if (i === lines.length - 1) speak("Accessibility audit complete.");
    }
    await new Promise((r) => setTimeout(r, 1000));
    setActiveIndex(0);
    onComplete();
  };

  const handleDownload = () => {
    speak("Downloading audit report to your laptop.");
    const content = `Accessibility Audit Report\n\nURL: ${selectedUrl || 'Unknown'}\nTest: ${selectedTest || 'Unknown'}\n\nIssues Found: 3\nScore: 92/100\n\nGenerated by Blink Income AI.`;
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "Accessibility_Audit.md";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getCurrentOptions = () => {
    if (appState === "MAIN_MENU") {
      return [
        { label: "Run Accessibility Audit", icon: ShieldAlert, action: () => { setAppState("URL_SELECT"); setActiveIndex(0); } },
        { label: "Exit Tester", icon: ChevronLeft, action: onExit },
      ];
    } else if (appState === "URL_SELECT") {
      const urls = ["Client Website A", "E-Commerce Portal B", "Government Site C", "Local Hospital Site"];
      return [
        ...urls.map(u => ({
          label: u, icon: Globe, action: () => {
            setSelectedUrl(u);
            setAppState("TEST_SELECT");
            setActiveIndex(0);
            speak(`Selected ${u}. What type of audit do you want to run?`);
          }
        })),
        { label: "Go Back", icon: ChevronLeft, action: () => { setAppState("MAIN_MENU"); setActiveIndex(0); } }
      ];
    } else if (appState === "TEST_SELECT") {
      const tests = ["Full WCAG 2.1 AA Audit", "Screen Reader Compatibility", "Keyboard Navigation Test", "Color Contrast Check"];
      return [
        ...tests.map(t => ({
          label: t, icon: Accessibility, action: () => {
            setSelectedTest(t);
            speak(`Running ${t} on ${selectedUrl}.`);
            simulateTerminal([
              "> Initializing Headless Browser...",
              `> Loading DOM tree for ${selectedUrl}...`,
              "> Simulating Keyboard Navigation (Tab Index Check)...",
              "> Scanning ARIA labels and alt-texts...",
              "> Analyzing DOM for WCAG Contrast Failures...",
              "> Compiling Engineering Report..."
            ], () => setAppState("RESULTS_VIEW"));
          }
        })),
        { label: "Go Back", icon: ChevronLeft, action: () => { setAppState("URL_SELECT"); setActiveIndex(0); } }
      ];
    } else if (appState === "RESULTS_VIEW") {
      return [
        { label: "Download as File", icon: Download, action: handleDownload },
        { label: "Export to Email", icon: Rocket, action: () => { speak("Audit report sent to your email."); } },
        { label: "Run Another Audit", icon: Accessibility, action: () => { setAppState("MAIN_MENU"); setActiveIndex(0); } },
        { label: "Exit Tester", icon: ChevronLeft, action: onExit },
      ];
    }
    return [];
  };

  const currentOptions = getCurrentOptions();

  const stopScanner = () => {
    if (intervalRef.current) window.clearInterval(intervalRef.current);
    setProgress(0);
  };

  const DWELL_TIME_MS = 5000;

  const startScanner = () => {
    stopScanner();
    const startTime = Date.now();
    intervalRef.current = window.setInterval(() => {
      const elapsed = Date.now() - startTime;
      const p = Math.min((elapsed / DWELL_TIME_MS) * 100, 100);
      setProgress(p);

      if (p >= 100) {
        stopScanner();
        const option = currentOptionsRef.current[activeIndexRef.current];
        if (option && option.action) {
          option.action();
        }
      }
    }, 50);
  };

  useEffect(() => {
    if (isActive && appState !== "GENERATING_VIEW") {
      startScanner();
    } else {
      stopScanner();
    }
    return stopScanner;
  }, [isActive, appState, currentOptions.length]);

  const activeIndexRef = useRef(activeIndex);
  activeIndexRef.current = activeIndex;
  const currentOptionsRef = useRef(currentOptions);
  currentOptionsRef.current = currentOptions;
  const startScannerRef = useRef(startScanner);
  startScannerRef.current = startScanner;

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.repeat) return;
      if (!isActive || e.code !== "Space" || appState === "GENERATING_VIEW") return;
      e.preventDefault();

      setActiveIndex((prev) => (prev + 1) % currentOptionsRef.current.length);
      setProgress(0);
      startScannerRef.current();
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isActive, appState]);

  useEffect(() => {
    const el = document.getElementById(`access-opt-${activeIndex}`);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [activeIndex]);

  if (!isActive) return null;

  return (
    <div className="absolute inset-0 z-50 bg-[#0B1121] flex overflow-hidden font-sans rounded-3xl text-white">
      <div className="w-[360px] flex-shrink-0 flex flex-col gap-4 bg-slate-900/80 p-6 border-r border-slate-800 shadow-2xl z-10 overflow-y-auto">
        <div className="mb-6">
          <h2 className="text-3xl font-black text-white flex items-center gap-3">
            <Accessibility className="w-8 h-8 text-lime-400" />
            Audit AI
          </h2>
        </div>

        <div className="flex flex-col gap-3 pb-8">
          {currentOptions.map((opt, idx) => (
            <motion.div
              key={opt.label}
              id={`access-opt-${idx}`}
              animate={{
                scale: activeIndex === idx ? 1.02 : 1,
                x: activeIndex === idx ? 10 : 0
              }}
              className={`relative p-4 rounded-2xl flex items-center gap-4 transition-all overflow-hidden ${
                activeIndex === idx 
                  ? "bg-lime-600 shadow-[0_0_20px_rgba(132,204,22,0.3)] text-white" 
                  : "bg-slate-800/50 text-slate-300 border border-slate-700/50"
              }`}
            >
              {activeIndex === idx && (
                <div 
                  className="absolute bottom-0 left-0 h-1 bg-white" 
                  style={{ width: `${progress}%`, transition: "width 50ms linear" }} 
                />
              )}
              <div className="shrink-0 flex items-center justify-center">
                {opt.icon ? <opt.icon className="w-6 h-6" /> : <div className="w-6 h-6 rounded-full border-2 border-current opacity-30" />}
              </div>
              <span className="font-bold text-[15px]">{opt.label}</span>
            </motion.div>
          ))}
        </div>
      </div>

      <div className="flex-1 relative flex flex-col bg-[#0B1121] p-8 overflow-y-auto items-center justify-center">
        <AnimatePresence mode="wait">
          {appState === "MAIN_MENU" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <Accessibility className="w-24 h-24 text-lime-500 mx-auto mb-6 opacity-80" />
              <h1 className="text-5xl font-black mb-4">Accessibility Tester</h1>
              <p className="text-xl text-slate-400 max-w-lg mx-auto">Generate professional WCAG compliance reports for any website.</p>
            </motion.div>
          )}

          {appState === "URL_SELECT" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <h1 className="text-4xl font-black mb-4">Select Target Website</h1>
              <p className="text-lg text-slate-400">Which client website are we analyzing today?</p>
            </motion.div>
          )}

          {appState === "TEST_SELECT" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <h1 className="text-4xl font-black mb-4">Select Audit Type</h1>
              <p className="text-lg text-slate-400">What specific accessibility rules should the AI verify?</p>
            </motion.div>
          )}

          {appState === "GENERATING_VIEW" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="w-full max-w-3xl">
              <div className="bg-black/80 rounded-xl p-6 font-mono text-lime-400 shadow-[0_0_30px_rgba(132,204,22,0.15)] border border-lime-500/20">
                <div className="flex items-center gap-2 mb-4 border-b border-lime-500/20 pb-4">
                  <div className="w-3 h-3 rounded-full bg-red-500" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500" />
                  <div className="w-3 h-3 rounded-full bg-lime-500" />
                  <span className="ml-2 text-lime-500/50 text-sm">ai-wcag-analyzer</span>
                </div>
                <div className="space-y-2 text-sm md:text-base">
                  {terminalLines.map((line, i) => (
                    <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}>
                      {line}
                    </motion.div>
                  ))}
                  <motion.div
                    animate={{ opacity: [1, 0] }}
                    transition={{ repeat: Infinity, duration: 0.8 }}
                    className="inline-block w-2 h-5 bg-lime-400 ml-2 align-middle"
                  />
                </div>
              </div>
            </motion.div>
          )}

          {appState === "RESULTS_VIEW" && (
            <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="w-full max-w-3xl text-center">
              <div className="inline-flex items-center justify-center w-24 h-24 rounded-full bg-lime-500/20 mb-6">
                <CheckCircle2 className="w-12 h-12 text-lime-400" />
              </div>
              <h1 className="text-4xl font-black mb-6">Audit Complete!</h1>
              <div className="bg-slate-800/50 border border-slate-700/50 rounded-2xl p-6 mb-8 text-left">
                <h3 className="font-bold text-slate-300 mb-2">Audit Summary:</h3>
                <ul className="space-y-2 text-slate-400">
                  <li>• Target: {selectedUrl}</li>
                  <li>• Test: {selectedTest}</li>
                  <li>• Issues Found: 14 Critical, 32 Minor</li>
                  <li>• Status: Engineering Report Generated</li>
                </ul>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
