import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronLeft, Search, FileText, CheckCircle2, Globe, Download, Rocket } from "lucide-react";

interface BlinkResearchAssistantProps {
  isActive: boolean;
  onExit: () => void;
}

export default function BlinkResearchAssistant({ isActive, onExit }: BlinkResearchAssistantProps) {
  const [appState, setAppState] = useState<"MAIN_MENU" | "TOPIC_SELECT" | "GENERATING_VIEW" | "RESULTS_VIEW">("MAIN_MENU");
  const [activeIndex, setActiveIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const [selectedTopic, setSelectedTopic] = useState<string | null>(null);

  const [terminalLines, setTerminalLines] = useState<string[]>([]);
  const intervalRef = useRef<number | null>(null);

  const synth = typeof window !== "undefined" ? window.speechSynthesis : null;
  const speak = (text: string) => {
    if (!synth) return;
    synth.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    synth.speak(utterance);
  };

  const simulateTerminal = async (lines: string[], onComplete: () => void) => {
    setAppState("GENERATING_VIEW");
    setTerminalLines([]);
    for (let i = 0; i < lines.length; i++) {
      await new Promise((r) => setTimeout(r, 600));
      setTerminalLines((prev) => [...prev, lines[i]]);
      if (i === lines.length - 1) speak("Research report complete.");
    }
    await new Promise((r) => setTimeout(r, 1000));
    setActiveIndex(0);
    onComplete();
  };

  const handleDownload = () => {
    speak("Downloading research report to your laptop.");
    const content = `# Research Report: ${selectedTopic}\n\nDepth: Comprehensive\n\nGenerated by Blink Income AI.\n\n- Executive Summary\n- Key Findings\n- Market Analysis\n- References`;
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "Research_Report.md";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getCurrentOptions = () => {
    if (appState === "MAIN_MENU") {
      return [
        { label: "Start New Research", icon: Search, action: () => { setAppState("TOPIC_SELECT"); setActiveIndex(0); } },
        { label: "Exit Research Assistant", icon: ChevronLeft, action: onExit },
      ];
    } else if (appState === "TOPIC_SELECT") {
      const topics = ["AI in Healthcare", "Global EV Market 2026", "Quantum Computing", "Future of Remote Work", "Space Tourism Economy"];
      return [
        ...topics.map(t => ({
          label: t, icon: Globe, action: () => {
            setSelectedTopic(t);
            speak(`Selected ${t}. Commencing deep web search.`);
            simulateTerminal([
              "> Initializing web scrapers...",
              `> Searching academic journals for: ${t}...`,
              "> Analyzing 452 related articles...",
              "> Synthesizing key findings...",
              "> Formatting into Markdown report...",
              "> Generating bibliography..."
            ], () => setAppState("RESULTS_VIEW"));
          }
        })),
        { label: "Go Back", icon: ChevronLeft, action: () => { setAppState("MAIN_MENU"); setActiveIndex(0); } }
      ];
    } else if (appState === "RESULTS_VIEW") {
      return [
        { label: "Download as File", icon: Download, action: handleDownload },
        { label: "Export to Email", icon: Rocket, action: () => { speak("Research report sent to your email."); } },
        { label: "Create Another", icon: Search, action: () => { setAppState("MAIN_MENU"); setActiveIndex(0); } },
        { label: "Exit Assistant", icon: ChevronLeft, action: onExit },
      ];
    }
    return [];
  };

  const currentOptions = getCurrentOptions();

  const stopScanner = () => {
    if (intervalRef.current) window.clearInterval(intervalRef.current);
    setProgress(0);
  };

  const DWELL_TIME_MS = 5000;

  const startScanner = () => {
    stopScanner();
    const startTime = Date.now();
    intervalRef.current = window.setInterval(() => {
      const elapsed = Date.now() - startTime;
      const p = Math.min((elapsed / DWELL_TIME_MS) * 100, 100);
      setProgress(p);

      if (p >= 100) {
        stopScanner();
        const option = currentOptionsRef.current[activeIndexRef.current];
        if (option && option.action) {
          option.action();
        }
      }
    }, 50);
  };

  useEffect(() => {
    if (isActive && appState !== "GENERATING_VIEW") {
      startScanner();
    } else {
      stopScanner();
    }
    return stopScanner;
  }, [isActive, appState, currentOptions.length]);

  const activeIndexRef = useRef(activeIndex);
  activeIndexRef.current = activeIndex;
  const currentOptionsRef = useRef(currentOptions);
  currentOptionsRef.current = currentOptions;
  const startScannerRef = useRef(startScanner);
  startScannerRef.current = startScanner;

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.repeat) return;
      if (!isActive || e.code !== "Space" || appState === "GENERATING_VIEW") return;
      e.preventDefault();

      setActiveIndex((prev) => (prev + 1) % currentOptionsRef.current.length);
      setProgress(0);
      startScannerRef.current();
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isActive, appState]);

  useEffect(() => {
    const el = document.getElementById(`research-opt-${activeIndex}`);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [activeIndex]);

  if (!isActive) return null;

  return (
    <div className="absolute inset-0 z-50 bg-[#0B1121] flex overflow-hidden font-sans rounded-3xl text-white">
      <div className="w-[360px] flex-shrink-0 flex flex-col gap-4 bg-slate-900/80 p-6 border-r border-slate-800 shadow-2xl z-10 overflow-y-auto">
        <div className="mb-6">
          <h2 className="text-3xl font-black text-white flex items-center gap-3">
            <Search className="w-8 h-8 text-purple-400" />
            AI Researcher
          </h2>
        </div>

        <div className="flex flex-col gap-3 pb-8">
          {currentOptions.map((opt, idx) => (
            <motion.div
              key={opt.label}
              id={`research-opt-${idx}`}
              animate={{
                scale: activeIndex === idx ? 1.02 : 1,
                x: activeIndex === idx ? 10 : 0
              }}
              className={`relative p-4 rounded-2xl flex items-center gap-4 transition-all overflow-hidden ${
                activeIndex === idx 
                  ? "bg-purple-600 shadow-[0_0_20px_rgba(147,51,234,0.3)] text-white" 
                  : "bg-slate-800/50 text-slate-300 border border-slate-700/50"
              }`}
            >
              {activeIndex === idx && (
                <div 
                  className="absolute bottom-0 left-0 h-1 bg-white" 
                  style={{ width: `${progress}%`, transition: "width 50ms linear" }} 
                />
              )}
              <div className="shrink-0 flex items-center justify-center">
                {opt.icon ? <opt.icon className="w-6 h-6" /> : <div className="w-6 h-6 rounded-full border-2 border-current opacity-30" />}
              </div>
              <span className="font-bold text-[15px]">{opt.label}</span>
            </motion.div>
          ))}
        </div>
      </div>

      <div className="flex-1 relative flex flex-col bg-[#0B1121] p-8 overflow-y-auto items-center justify-center">
        <AnimatePresence mode="wait">
          {appState === "MAIN_MENU" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <Globe className="w-24 h-24 text-purple-500 mx-auto mb-6 opacity-80" />
              <h1 className="text-5xl font-black mb-4">AI Research Assistant</h1>
              <p className="text-xl text-slate-400 max-w-lg mx-auto">Generate comprehensive research reports instantly with a single blink.</p>
            </motion.div>
          )}

          {appState === "TOPIC_SELECT" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <h1 className="text-4xl font-black mb-4">Select Research Topic</h1>
              <p className="text-lg text-slate-400">The AI will scour the web and academic sources for this subject.</p>
            </motion.div>
          )}

          {appState === "GENERATING_VIEW" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="w-full max-w-3xl">
              <div className="bg-black/80 rounded-xl p-6 font-mono text-purple-400 shadow-[0_0_30px_rgba(147,51,234,0.15)] border border-purple-500/20">
                <div className="flex items-center gap-2 mb-4 border-b border-purple-500/20 pb-4">
                  <div className="w-3 h-3 rounded-full bg-red-500" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500" />
                  <div className="w-3 h-3 rounded-full bg-purple-500" />
                  <span className="ml-2 text-purple-500/50 text-sm">ai-spider-engine</span>
                </div>
                <div className="space-y-2 text-sm md:text-base">
                  {terminalLines.map((line, i) => (
                    <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}>
                      {line}
                    </motion.div>
                  ))}
                  <motion.div
                    animate={{ opacity: [1, 0] }}
                    transition={{ repeat: Infinity, duration: 0.8 }}
                    className="inline-block w-2 h-5 bg-purple-400 ml-2 align-middle"
                  />
                </div>
              </div>
            </motion.div>
          )}

          {appState === "RESULTS_VIEW" && (
            <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="w-full max-w-3xl text-center">
              <div className="inline-flex items-center justify-center w-24 h-24 rounded-full bg-purple-500/20 mb-6">
                <CheckCircle2 className="w-12 h-12 text-purple-400" />
              </div>
              <h1 className="text-4xl font-black mb-6">Research Report Ready!</h1>
              <div className="bg-slate-800/50 border border-slate-700/50 rounded-2xl p-6 mb-8 text-left">
                <h3 className="font-bold text-slate-300 mb-2">Report Summary:</h3>
                <ul className="space-y-2 text-slate-400">
                  <li>• Topic: {selectedTopic}</li>
                  <li>• Length: ~15 Pages</li>
                  <li>• Citations: 42 Validated Sources</li>
                </ul>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
