import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronLeft, LayoutTemplate, Palette, Rocket, CheckCircle2, MonitorSmartphone, Download } from "lucide-react";

interface BlinkWebsiteBuilderProps {
  isActive: boolean;
  onExit: () => void;
}

export default function BlinkWebsiteBuilder({ isActive, onExit }: BlinkWebsiteBuilderProps) {
  const [appState, setAppState] = useState<"MAIN_MENU" | "BUSINESS_SELECT" | "THEME_SELECT" | "GENERATING_VIEW" | "RESULTS_VIEW">("MAIN_MENU");
  const [activeIndex, setActiveIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const [selectedBusiness, setSelectedBusiness] = useState<string | null>(null);
  const [selectedTheme, setSelectedTheme] = useState<string | null>(null);

  const [terminalLines, setTerminalLines] = useState<string[]>([]);

  const intervalRef = useRef<number | null>(null);

  const synth = typeof window !== "undefined" ? window.speechSynthesis : null;
  const speak = (text: string) => {
    if (!synth) return;
    synth.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    synth.speak(utterance);
  };

  const simulateTerminal = async (lines: string[], onComplete: () => void) => {
    setAppState("GENERATING_VIEW");
    setTerminalLines([]);
    for (let i = 0; i < lines.length; i++) {
      await new Promise((r) => setTimeout(r, 600));
      setTerminalLines((prev) => [...prev, lines[i]]);
      if (i === lines.length - 1) speak("Website generation complete.");
    }
    await new Promise((r) => setTimeout(r, 1000));
    setActiveIndex(0);
    onComplete();
  };

  const handleDownload = () => {
    speak("Downloading website package to your laptop.");
    const content = `<!DOCTYPE html>
<html>
<head>
  <title>${selectedBusiness} Website</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <h1>Welcome to ${selectedBusiness}</h1>
  <p>Theme: ${selectedTheme}</p>
  <p>Generated by Blink Income AI.</p>
</body>
</html>`;
    const blob = new Blob([content], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "index.html";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getCurrentOptions = () => {
    if (appState === "MAIN_MENU") {
      return [
        { label: "Create New Website", icon: LayoutTemplate, action: () => { setAppState("BUSINESS_SELECT"); setActiveIndex(0); } },
        { label: "Exit Website Builder", icon: ChevronLeft, action: onExit },
      ];
    } else if (appState === "BUSINESS_SELECT") {
      const businesses = ["Advocate / Law Firm", "Gym / Fitness Center", "Beauty Salon", "Local Restaurant", "Digital Marketing Agency"];
      return [
        ...businesses.map(b => ({
          label: b, icon: LayoutTemplate, action: () => {
            setSelectedBusiness(b);
            setAppState("THEME_SELECT");
            setActiveIndex(0);
            speak(`Selected ${b}. Please select a design theme.`);
          }
        })),
        { label: "Go Back", icon: ChevronLeft, action: () => { setAppState("MAIN_MENU"); setActiveIndex(0); } }
      ];
    } else if (appState === "THEME_SELECT") {
      const themes = ["Dark & Premium", "Clean & Minimal", "Vibrant & Playful", "Corporate Professional"];
      return [
        ...themes.map(t => ({
          label: t, icon: Palette, action: () => {
            setSelectedTheme(t);
            speak(`Selected ${t} theme. Starting AI Generation.`);
            simulateTerminal([
              "> Initializing HTML5 boilerplate...",
              `> Generating CSS styles for ${t}...`,
              `> Drafting copy for ${selectedBusiness}...`,
              "> Injecting responsive flexbox & grid layouts...",
              "> Optimizing mobile viewport...",
              "> Packing Website Code into ZIP..."
            ], () => setAppState("RESULTS_VIEW"));
          }
        })),
        { label: "Go Back", icon: ChevronLeft, action: () => { setAppState("BUSINESS_SELECT"); setActiveIndex(0); } }
      ];
    } else if (appState === "RESULTS_VIEW") {
      return [
        { label: "Download as File", icon: Download, action: handleDownload },
        { label: "Export to Email", icon: Rocket, action: () => { speak("Website code sent to your email."); } },
        { label: "Create Another", icon: LayoutTemplate, action: () => { setAppState("MAIN_MENU"); setActiveIndex(0); } },
        { label: "Exit Website Builder", icon: ChevronLeft, action: onExit },
      ];
    }
    return [];
  };

  const currentOptions = getCurrentOptions();

  const stopScanner = () => {
    if (intervalRef.current) window.clearInterval(intervalRef.current);
    setProgress(0);
  };

  const DWELL_TIME_MS = 5000;

  const startScanner = () => {
    stopScanner();
    const startTime = Date.now();
    intervalRef.current = window.setInterval(() => {
      const elapsed = Date.now() - startTime;
      const p = Math.min((elapsed / DWELL_TIME_MS) * 100, 100);
      setProgress(p);

      if (p >= 100) {
        stopScanner();
        const option = currentOptionsRef.current[activeIndexRef.current];
        if (option && option.action) {
          option.action();
        }
      }
    }, 50);
  };

  useEffect(() => {
    if (isActive && appState !== "GENERATING_VIEW") {
      startScanner();
    } else {
      stopScanner();
    }
    return stopScanner;
  }, [isActive, appState, currentOptions.length]);

  const activeIndexRef = useRef(activeIndex);
  activeIndexRef.current = activeIndex;
  const currentOptionsRef = useRef(currentOptions);
  currentOptionsRef.current = currentOptions;
  const startScannerRef = useRef(startScanner);
  startScannerRef.current = startScanner;

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.repeat) return;
      if (!isActive || e.code !== "Space" || appState === "GENERATING_VIEW") return;
      e.preventDefault();

      setActiveIndex((prev) => (prev + 1) % currentOptionsRef.current.length);
      setProgress(0);
      startScannerRef.current();
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isActive, appState]);

  useEffect(() => {
    const el = document.getElementById(`web-opt-${activeIndex}`);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [activeIndex]);

  if (!isActive) return null;

  return (
    <div className="absolute inset-0 z-50 bg-slate-900 flex overflow-hidden font-sans rounded-3xl text-white">
      <div className="w-[360px] flex-shrink-0 flex flex-col gap-4 bg-slate-900/80 p-6 border-r border-slate-800 shadow-2xl z-10 overflow-y-auto">
        <div className="mb-6">
          <h2 className="text-3xl font-black text-white flex items-center gap-3">
            <MonitorSmartphone className="w-8 h-8 text-emerald-400" />
            Website AI
          </h2>
        </div>

        <div className="flex flex-col gap-3 pb-8">
          {currentOptions.map((opt, idx) => (
            <motion.div
              key={opt.label}
              id={`web-opt-${idx}`}
              animate={{
                scale: activeIndex === idx ? 1.02 : 1,
                x: activeIndex === idx ? 10 : 0
              }}
              className={`relative p-4 rounded-2xl flex items-center gap-4 transition-all overflow-hidden ${
                activeIndex === idx 
                  ? "bg-emerald-600 shadow-[0_0_20px_rgba(16,185,129,0.3)] text-white" 
                  : "bg-slate-800/50 text-slate-300 border border-slate-700/50"
              }`}
            >
              {activeIndex === idx && (
                <div 
                  className="absolute bottom-0 left-0 h-1 bg-white" 
                  style={{ width: `${progress}%`, transition: "width 50ms linear" }} 
                />
              )}
              <div className="shrink-0 flex items-center justify-center">
                {opt.icon ? <opt.icon className="w-6 h-6" /> : <div className="w-6 h-6 rounded-full border-2 border-current opacity-30" />}
              </div>
              <span className="font-bold text-[15px]">{opt.label}</span>
            </motion.div>
          ))}
        </div>
      </div>

      <div className="flex-1 relative flex flex-col bg-[#0B1121] p-8 overflow-y-auto items-center justify-center">
        <AnimatePresence mode="wait">
          {appState === "MAIN_MENU" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <MonitorSmartphone className="w-24 h-24 text-emerald-500 mx-auto mb-6 opacity-80" />
              <h1 className="text-5xl font-black mb-4">Website Builder</h1>
              <p className="text-xl text-slate-400 max-w-lg mx-auto">Generate fully responsive HTML & CSS websites in seconds with your spacebar.</p>
            </motion.div>
          )}

          {appState === "BUSINESS_SELECT" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <h1 className="text-4xl font-black mb-4">Select Target Audience</h1>
              <p className="text-lg text-slate-400">The AI will customize the website copy for this industry.</p>
            </motion.div>
          )}

          {appState === "THEME_SELECT" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <h1 className="text-4xl font-black mb-4">Select Design Theme</h1>
              <p className="text-lg text-slate-400">Choose the aesthetic vibe for your client&apos;s brand.</p>
            </motion.div>
          )}

          {appState === "GENERATING_VIEW" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="w-full max-w-3xl">
              <div className="bg-black/80 rounded-xl p-6 font-mono text-emerald-400 shadow-[0_0_30px_rgba(16,185,129,0.15)] border border-emerald-500/20">
                <div className="flex items-center gap-2 mb-4 border-b border-emerald-500/20 pb-4">
                  <div className="w-3 h-3 rounded-full bg-red-500" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500" />
                  <div className="w-3 h-3 rounded-full bg-emerald-500" />
                  <span className="ml-2 text-emerald-500/50 text-sm">ai-web-compiler</span>
                </div>
                <div className="space-y-2 text-sm md:text-base">
                  {terminalLines.map((line, i) => (
                    <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}>
                      {line}
                    </motion.div>
                  ))}
                  <motion.div
                    animate={{ opacity: [1, 0] }}
                    transition={{ repeat: Infinity, duration: 0.8 }}
                    className="inline-block w-2 h-5 bg-emerald-400 ml-2 align-middle"
                  />
                </div>
              </div>
            </motion.div>
          )}

          {appState === "RESULTS_VIEW" && (
            <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="w-full max-w-3xl text-center">
              <div className="inline-flex items-center justify-center w-24 h-24 rounded-full bg-emerald-500/20 mb-6">
                <CheckCircle2 className="w-12 h-12 text-emerald-400" />
              </div>
              <h1 className="text-4xl font-black mb-6">Website Package Ready!</h1>
              <div className="bg-slate-800/50 border border-slate-700/50 rounded-2xl p-6 mb-8 text-left">
                <h3 className="font-bold text-slate-300 mb-2">Package Details:</h3>
                <ul className="space-y-2 text-slate-400">
                  <li>• Industry: {selectedBusiness}</li>
                  <li>• Theme: {selectedTheme}</li>
                  <li>• Contents: index.html, style.css, assets/</li>
                </ul>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
