import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronLeft, Presentation, CheckCircle2, TrendingUp, Lightbulb, Rocket, Download } from "lucide-react";
import emailjs from '@emailjs/browser';

interface BlinkPitchDeckProps {
  isActive: boolean;
  onExit: () => void;
}

export default function BlinkPitchDeck({ isActive, onExit }: BlinkPitchDeckProps) {
  const [appState, setAppState] = useState<"MAIN_MENU" | "INDUSTRY_SELECT" | "STAGE_SELECT" | "GENERATING_VIEW" | "RESULTS_VIEW">("MAIN_MENU");
  const [activeIndex, setActiveIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const [selectedIndustry, setSelectedIndustry] = useState<string | null>(null);
  const [selectedStage, setSelectedStage] = useState<string | null>(null);

  const [terminalLines, setTerminalLines] = useState<string[]>([]);
  const intervalRef = useRef<number | null>(null);

  const synth = typeof window !== "undefined" ? window.speechSynthesis : null;
  const speak = (text: string) => {
    if (!synth) return;
    synth.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    synth.speak(utterance);
  };

  const simulateTerminal = async (lines: string[], onComplete: () => void) => {
    setAppState("GENERATING_VIEW");
    setTerminalLines([]);
    for (let i = 0; i < lines.length; i++) {
      await new Promise((r) => setTimeout(r, 600));
      setTerminalLines((prev) => [...prev, lines[i]]);
      if (i === lines.length - 1) speak("Pitch deck generation complete.");
    }
    await new Promise((r) => setTimeout(r, 1000));
    setActiveIndex(0);
    onComplete();
  };

  const handleDownload = () => {
    speak("Downloading pitch deck to your laptop.");
    const content = `Pitch Deck: ${selectedIndustry} - ${selectedStage}

Slide 1: Problem Statement
Slide 2: Solution & Value Proposition
Slide 3: Market Size & Opportunity
Slide 4: Business Model
Slide 5: Go-to-Market Strategy
Slide 6: Competitive Landscape
Slide 7: Founding Team
Slide 8: Financial Projections
Slide 9: The Ask (Funding)
Slide 10: Vision & Roadmap

Generated by Blink Income AI.`;
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "Pitch_Deck.md";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleEmail = () => {
    speak("Sending email automatically via Email J S.");
    
    const templateParams = {
      to_email: "iitianadityakumarsingh@gmail.com",
      subject: `Pitch Deck: ${selectedIndustry} - ${selectedStage}`,
      message: `Here is the AI generated Pitch Deck for your ${selectedIndustry} startup at the ${selectedStage} stage.

Slide 1: Problem Statement
Slide 2: Solution & Value Proposition
Slide 3: Market Size & Opportunity
Slide 4: Business Model
Slide 5: Go-to-Market Strategy
Slide 6: Competitive Landscape
Slide 7: Founding Team
Slide 8: Financial Projections
Slide 9: The Ask (Funding)
Slide 10: Vision & Roadmap

Generated by Blink Income AI.`
    };

    emailjs.send(
      'service_t1r9h2k', 
      'template_b2hu1hb', 
      templateParams, 
      { publicKey: 'KLgvyqra8AbpRU5cP' }
    )
    .then((response) => {
      speak("Email successfully sent directly to your inbox.");
      console.log('SUCCESS!', response.status, response.text);
    })
    .catch((error) => {
      speak("Failed to send email.");
      alert(`EmailJS Error: ${error?.text || error?.message || JSON.stringify(error)}`);
      console.error("EmailJS Error:", error);
    });
  };

  const getCurrentOptions = () => {
    if (appState === "MAIN_MENU") {
      return [
        { label: "Create Pitch Deck", icon: Presentation, action: () => { setAppState("INDUSTRY_SELECT"); setActiveIndex(0); } },
        { label: "Exit Pitch Deck Creator", icon: ChevronLeft, action: onExit },
      ];
    } else if (appState === "INDUSTRY_SELECT") {
      const industries = ["B2B SaaS", "Fintech / Web3", "HealthTech", "E-Commerce", "EdTech"];
      return [
        ...industries.map(i => ({
          label: i, icon: Lightbulb, action: () => {
            setSelectedIndustry(i);
            setAppState("STAGE_SELECT");
            setActiveIndex(0);
            speak(`Selected ${i}. What is the current funding stage?`);
          }
        })),
        { label: "Go Back", icon: ChevronLeft, action: () => { setAppState("MAIN_MENU"); setActiveIndex(0); } }
      ];
    } else if (appState === "STAGE_SELECT") {
      const stages = ["Pre-Seed (Idea Stage)", "Seed (Early Traction)", "Series A (Scaling)", "Bootstrapped (Profitable)"];
      return [
        ...stages.map(s => ({
          label: s, icon: TrendingUp, action: () => {
            setSelectedStage(s);
            speak(`Selected ${s}. Generating VC-ready Pitch Deck.`);
            simulateTerminal([
              "> Analyzing top VC pitch decks in Y-Combinator database...",
              `> Drafting Problem/Solution statement for ${selectedIndustry}...`,
              "> Calculating TAM/SAM/SOM market size...",
              "> Structuring Financial Projections...",
              "> Writing Speaker Notes...",
              "> Exporting to PowerPoint & PDF formats..."
            ], () => setAppState("RESULTS_VIEW"));
          }
        })),
        { label: "Go Back", icon: ChevronLeft, action: () => { setAppState("INDUSTRY_SELECT"); setActiveIndex(0); } }
      ];
    } else if (appState === "RESULTS_VIEW") {
      return [
        { label: "Download as File", icon: Download, action: handleDownload },
        { label: "Export to Email", icon: Rocket, action: handleEmail },
        { label: "Create Another", icon: Presentation, action: () => { setAppState("MAIN_MENU"); setActiveIndex(0); } },
        { label: "Exit Pitch Deck Creator", icon: ChevronLeft, action: onExit },
      ];
    }
    return [];
  };

  const currentOptions = getCurrentOptions();

  const stopScanner = () => {
    if (intervalRef.current) window.clearInterval(intervalRef.current);
    setProgress(0);
  };

  const DWELL_TIME_MS = 5000;

  const startScanner = () => {
    stopScanner();
    const startTime = Date.now();
    intervalRef.current = window.setInterval(() => {
      const elapsed = Date.now() - startTime;
      const p = Math.min((elapsed / DWELL_TIME_MS) * 100, 100);
      setProgress(p);

      if (p >= 100) {
        stopScanner();
        const option = currentOptionsRef.current[activeIndexRef.current];
        if (option && option.action) {
          option.action();
        }
      }
    }, 50);
  };

  useEffect(() => {
    if (isActive && appState !== "GENERATING_VIEW") {
      startScanner();
    } else {
      stopScanner();
    }
    return stopScanner;
  }, [isActive, appState, currentOptions.length]);

  const activeIndexRef = useRef(activeIndex);
  activeIndexRef.current = activeIndex;
  const currentOptionsRef = useRef(currentOptions);
  currentOptionsRef.current = currentOptions;
  const startScannerRef = useRef(startScanner);
  startScannerRef.current = startScanner;

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.repeat) return;
      if (!isActive || e.code !== "Space" || appState === "GENERATING_VIEW") return;
      e.preventDefault();

      setActiveIndex((prev) => (prev + 1) % currentOptionsRef.current.length);
      setProgress(0);
      startScannerRef.current();
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isActive, appState]);

  useEffect(() => {
    const el = document.getElementById(`pitch-opt-${activeIndex}`);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [activeIndex]);

  if (!isActive) return null;

  return (
    <div className="absolute inset-0 z-50 bg-[#0B1121] flex overflow-hidden font-sans rounded-3xl text-white">
      <div className="w-[360px] flex-shrink-0 flex flex-col gap-4 bg-slate-900/80 p-6 border-r border-slate-800 shadow-2xl z-10 overflow-y-auto">
        <div className="mb-6">
          <h2 className="text-3xl font-black text-white flex items-center gap-3">
            <Presentation className="w-8 h-8 text-cyan-400" />
            Pitch AI
          </h2>
        </div>

        <div className="flex flex-col gap-3 pb-8">
          {currentOptions.map((opt, idx) => (
            <motion.div
              key={opt.label}
              id={`pitch-opt-${idx}`}
              animate={{
                scale: activeIndex === idx ? 1.02 : 1,
                x: activeIndex === idx ? 10 : 0
              }}
              className={`relative p-4 rounded-2xl flex items-center gap-4 transition-all overflow-hidden ${
                activeIndex === idx 
                  ? "bg-cyan-600 shadow-[0_0_20px_rgba(34,211,238,0.3)] text-white" 
                  : "bg-slate-800/50 text-slate-300 border border-slate-700/50"
              }`}
            >
              {activeIndex === idx && (
                <div 
                  className="absolute bottom-0 left-0 h-1 bg-white" 
                  style={{ width: `${progress}%`, transition: "width 50ms linear" }} 
                />
              )}
              <div className="shrink-0 flex items-center justify-center">
                {opt.icon ? <opt.icon className="w-6 h-6" /> : <div className="w-6 h-6 rounded-full border-2 border-current opacity-30" />}
              </div>
              <span className="font-bold text-[15px]">{opt.label}</span>
            </motion.div>
          ))}
        </div>
      </div>

      <div className="flex-1 relative flex flex-col bg-[#0B1121] p-8 overflow-y-auto items-center justify-center">
        <AnimatePresence mode="wait">
          {appState === "MAIN_MENU" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <Presentation className="w-24 h-24 text-cyan-500 mx-auto mb-6 opacity-80" />
              <h1 className="text-5xl font-black mb-4">Pitch Deck Creator</h1>
              <p className="text-xl text-slate-400 max-w-lg mx-auto">Generate investor-ready 10-slide pitch decks structured by AI.</p>
            </motion.div>
          )}

          {appState === "INDUSTRY_SELECT" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <h1 className="text-4xl font-black mb-4">Select Startup Industry</h1>
              <p className="text-lg text-slate-400">This helps the AI identify target markets and standard business models.</p>
            </motion.div>
          )}

          {appState === "STAGE_SELECT" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center">
              <h1 className="text-4xl font-black mb-4">Select Funding Stage</h1>
              <p className="text-lg text-slate-400">The AI will adjust the focus (e.g. idea vs traction) based on stage.</p>
            </motion.div>
          )}

          {appState === "GENERATING_VIEW" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="w-full max-w-3xl">
              <div className="bg-black/80 rounded-xl p-6 font-mono text-cyan-400 shadow-[0_0_30px_rgba(34,211,238,0.15)] border border-cyan-500/20">
                <div className="flex items-center gap-2 mb-4 border-b border-cyan-500/20 pb-4">
                  <div className="w-3 h-3 rounded-full bg-red-500" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500" />
                  <div className="w-3 h-3 rounded-full bg-cyan-500" />
                  <span className="ml-2 text-cyan-500/50 text-sm">ai-deck-builder</span>
                </div>
                <div className="space-y-2 text-sm md:text-base">
                  {terminalLines.map((line, i) => (
                    <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}>
                      {line}
                    </motion.div>
                  ))}
                  <motion.div
                    animate={{ opacity: [1, 0] }}
                    transition={{ repeat: Infinity, duration: 0.8 }}
                    className="inline-block w-2 h-5 bg-cyan-400 ml-2 align-middle"
                  />
                </div>
              </div>
            </motion.div>
          )}

          {appState === "RESULTS_VIEW" && (
            <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="w-full max-w-4xl text-left">
              <div className="flex items-center gap-4 mb-6">
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-cyan-500/20">
                  <CheckCircle2 className="w-8 h-8 text-cyan-400" />
                </div>
                <div>
                  <h1 className="text-3xl font-black">Pitch Deck Generated!</h1>
                  <p className="text-slate-400">{selectedIndustry} • {selectedStage}</p>
                </div>
              </div>
              
              <div className="bg-slate-800/50 border border-slate-700/50 rounded-2xl p-6 mb-8 overflow-y-auto max-h-[50vh] pr-4 custom-scrollbar">
                <h3 className="font-bold text-cyan-300 text-xl mb-6 flex items-center gap-2">
                  <Presentation className="w-5 h-5" />
                  10-Slide Deck Outline
                </h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {[
                    { title: "1. Problem", desc: `Why the current ${selectedIndustry} solutions are failing.` },
                    { title: "2. Solution", desc: "Our unique value proposition and product." },
                    { title: "3. Market Size", desc: "TAM, SAM, and SOM analysis." },
                    { title: "4. Business Model", desc: "How we make money and unit economics." },
                    { title: "5. Traction", desc: `Current metrics for ${selectedStage} stage.` },
                    { title: "6. Go-To-Market", desc: "Acquisition strategy and distribution channels." },
                    { title: "7. Competition", desc: "Competitive matrix and our unfair advantage." },
                    { title: "8. Team", desc: "Why we are the right people to build this." },
                    { title: "9. Financials", desc: "3-year projections and cash flow." },
                    { title: "10. The Ask", desc: "Funding requirements and milestones." }
                  ].map((slide, i) => (
                    <div key={i} className="bg-slate-900/80 p-4 rounded-xl border border-slate-700/50">
                      <h4 className="font-bold text-white mb-1">{slide.title}</h4>
                      <p className="text-sm text-slate-400">{slide.desc}</p>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
